name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
      - run: mkdir secrets
      - name: Create certificate
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'benchilcott.com.pem'
          fileDir: './secrets/'
          encodedString: ${{ secrets.SSL_CERTIFICATE }}
      - name: Create key
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'benchilcott.com.key'
          fileDir: './secrets/'
          encodedString: ${{ secrets.SSL_KEY }}
